apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  volumes:
  - name: secrets-vol
    secret:
      secretName: db-passwords
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo DB_PASS=$DATABASE_PASSWORD && sleep 3600"]
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-passwords
          key: db-password
    volumeMounts:
    - name: secrets-vol
      mountPath: /etc/db-passwords
