apiVersion: v1
kind: Service
metadata:
  name: nginx-green-test
spec:
  type: LoadBalancer
  selector: { app: nginx, role: green }    # Service RIÊNG cho dev test green — user thật không dùng
  ports: [{ port: 9001, targetPort: 80 }]  # cổng 9001 tách biệt cổng 80 public
