apiVersion: v1
kind: Service
metadata:
  name: web-clusterip
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - port: 8080        # caller gọi cổng 8080
    targetPort: 80    # container nginx nghe cổng 80
